# Generated by Django 5.0.6 on 2024-06-28 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ob_app', '0018_alter_role_rolename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allkeys',
            name='accountIDS',
            field=models.ManyToManyField(blank=True, to='ob_app.account'),
        ),
        migrations.AlterField(
            model_name='allkeys',
            name='employeeID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ob_app.employee'),
        ),
        migrations.AlterField(
            model_name='allkeys',
            name='installationIDS',
            field=models.ManyToManyField(blank=True, to='ob_app.installation'),
        ),
        migrations.AlterField(
            model_name='allkeys',
            name='licenseIDS',
            field=models.ManyToManyField(blank=True, to='ob_app.license'),
        ),
        migrations.AlterField(
            model_name='allkeys',
            name='materialIDS',
            field=models.ManyToManyField(blank=True, to='ob_app.material'),
        ),
        migrations.AlterField(
            model_name='allkeys',
            name='newEmployeeID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ob_app.newemployee'),
        ),
        migrations.AlterField(
            model_name='allkeys',
            name='otherIDS',
            field=models.ManyToManyField(blank=True, to='ob_app.other'),
        ),
        migrations.AlterField(
            model_name='role',
            name='rolename',
            field=models.CharField(max_length=100),
        ),
    ]
